spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ticket_service_db?createDatabaseIfNotExist=true
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

fixedDelaySeconds: 20
paymentService:
  url: http://localhost:8081/payments