spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ticket_service_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true

fixed_delay_seconds: 5